language: node_js
node_js:
  - "node"
  - "lts/*"
deploy:
  provider: npm
  email: ken@kendaleiv.com
  api_key:
    secure: wC8cQJt44wDRtSCWXzXl6CBjWLP3Qm/jGskO67Jeo2CvLNUTneXgUeJt9x1AMKnrZWC2h1RYK8zjL4sdiwry8C+GAP8cx+VPJk49JV49wk2zZTUE6o2mt765SxlJFvALqBCUQ2jp2hdDleyYZLWW5yBZyOB74R61GzWowqoNCNIkq8WvfmKQAHI4lsu+7bp1UwSz8YbsHnquqEN8A1NQiyZ5Fh5XhvWtdQ1Lv4gm3wzil7DrbqlrY7GtwCbk9tIn6UdvSGvIMiF+lDuwzchTYHJ7FvGJdnJ2zwFLG/VCqE5BG90ZTD2bah+IF2CupkVpjkcqUflZao9fmxiFIRvZkvDg2j4upZn8+Xjrg0pRIt6FGu7MDz20hw95DNXQK15NOhHJrLZ5Npd7YvAE7m3IhJa5nzAyWaoTjxvpZaoyWpqtc+Q3CMPapjesog37wEHg9azoeanr/l26jrUoQb7vw9gWK06TckhxEUgcCdzaUJeb3KKKZxKrsGBXKKVkvVCto57XQuJ7YhoxIZ0HpcT9cvlbz4Vhnz8pDuXM7pVeXHvd7FT7Zmhjr98ZINJuikw534eg/NKXJYtSAOzxMykREDspRssiwUQso5iKA7WJnw8xTtm13/BiLbBHFdSMTunxSc0YmyS8nzK8ZqBdVfo8AimXdkYtiE0fejcBfgRCqY4=
  on:
    branch: master
    repo: kendaleiv/giphy-search-component
